# Python Fundamentals

# Session 9

# Retail Sales Data Analysis — Pandas Project
In this project, you will use Python and Pandas to clean, transform, explore, and analyze a retail sales dataset.

The goal is to work with real-world business data and answer different business questions using Pandas.
## Data Exploration & Cleaning

* Read the data from the `data.csv` file.
* Explore the data
* Check for missing values.
* Check for duplicate records.
* Check the data types of all columns.
* Convert columns to the appropriate data types where necessary:

  * Convert `Invoice Date` to datetime.
  * Convert numeric and currency columns to numeric values.
* Create new columns from `Invoice Date`:

  * `day`
  * `month`
  * `year`
* Drop unnecessary columns such as `Retailer ID`.
* Handle missing values appropriately.
* Check the `Region` column and make sure there are no typos or inconsistent names.

---

# Business Analysis

Perform the following analysis using Pandas:

### Sales Analysis

1. What is the total sales? 

2. What is the average sales for every region?

3. What is the average sales for every product?

4. What is the count of each product?

5. What is the top product by total sales?

6. What is the lowest-performing product by total sales?

### Time Analysis

7. How many products were sold each year?

8. How have total sales changed over the years?

9. How do sales vary month over month?

### Retailer Analysis

10. Which retailer has the highest total sales?

11. Which retailer has the highest operating profit?

### Product & Profit Analysis

12. What is the most profitable product?

13. What is the average price per unit for each product?

### Geographic Analysis

14. Which region has the highest total sales?

15. Which city contributes the most to total sales?

## Data Exploration & Cleaning

In [1]:
import pandas as pd

* Read the data from the `data.csv` file.
* Explore the data

In [2]:
df = pd.read_csv('data.csv')
df

,Retailer,Retailer ID,Invoice Date,Region,State,city,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Sales Method
0,Foot Locker,1185732,1/1/2020,Northeast,New York,New York,Men's Street Footwear,$50.00,"1,200","60,000","$30,000",In-store
1,Foot Locker,1185732,1/2/2020,Northeast,New York,New York,Men's Athletic Footwear,$50.00,"1,000","50,000","$15,000",In-store
2,Foot Locker,1185732,1/3/2020,Northeast,New York,New York,Women's Street Footwear,$40.00,"1,000","40,000","$14,000",In-store
3,Foot Locker,1185732,1/4/2020,Northeast,New York,New York,Women's Athletic Footwear,$45.00,850,"38,250","$13,388",In-store
4,Foot Locker,1185732,1/5/2020,Northeast,New York,New York,Men's Apparel,$60.00,900,"54,000","$16,200",In-store
...,...,...,...,...,...,...,...,...,...,...,...,...
9656,Foot Locker,1185732,1/24/2021,Northeast,New Hampshire,Manchester,Men's Apparel,$50.00,64,320,$90,Outlet
9657,Foot Locker,1185732,1/24/2021,Northeast,New Hampshire,Manchester,Women's Apparel,$41.00,105,431,$138,Outlet
9658,Foot Locker,1185732,2/22/2021,Northeast,New Hampshire,Manchester,Men's Street Footwear,$41.00,184,754,$279,Outlet
9659,Foot Locker,1185732,2/22/2021,Northeast,New Hampshire,Manchester,Men's Athletic Footwear,$42.00,70,294,$123,Outlet
9660,Foot Locker,1185732,2/22/2021,Northeast,New Hampshire,Manchester,Women's Street Footwear,$29.00,83,241,$65,Outlet

* Check for missing values.

In [3]:
df.isnull().sum()

Retailer            0
Retailer ID         0
Invoice Date        0
  Region            7
State               0
city                0
Product             0
Price per Unit      2
Units Sold          0
Total Sales         0
Operating Profit    0
Sales Method        0
dtype: int64

* Check for duplicate records.

In [4]:
df.duplicated().sum()

13

* Check the data types of all columns.

In [5]:
df.dtypes

Retailer            object
Retailer ID          int64
Invoice Date        object
  Region            object
State               object
city                object
Product             object
Price per Unit      object
Units Sold          object
Total Sales         object
Operating Profit    object
Sales Method        object
dtype: object

* Convert columns to the appropriate data types where necessary:

  * Convert `Invoice Date` to datetime.
  * Convert numeric and currency columns to numeric values.

In [6]:
df['Invoice Date'] = pd.to_datetime(df['Invoice Date'])
df['Price per Unit'] = (
        df['Price per Unit']
        .str.strip()
        .str.replace('$', '')
        .str.replace(',', '')
        .astype(float)
)
df['Units Sold'] = (
        df['Units Sold']
        .str.strip()
        .str.replace('$', '')
        .str.replace(',', '')
        .astype(float)
)
df['Total Sales'] = (
        df['Total Sales']
        .str.strip()
        .str.replace('$', '')
        .str.replace(',', '')
        .astype(float)
)
df['Operating Profit'] = (
        df['Operating Profit']
        .str.strip()
        .str.replace('$', '')
        .str.replace(',', '')
        .astype(float)
)

In [7]:
print(df.dtypes)
df

Retailer                    object
Retailer ID                  int64
Invoice Date        datetime64[ns]
  Region                    object
State                       object
city                        object
Product                     object
Price per Unit             float64
Units Sold                 float64
Total Sales                float64
Operating Profit           float64
Sales Method                object
dtype: object

,Retailer,Retailer ID,Invoice Date,Region,State,city,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Sales Method
0,Foot Locker,1185732,2020-01-01,Northeast,New York,New York,Men's Street Footwear,50.0,1200.0,60000.0,30000.0,In-store
1,Foot Locker,1185732,2020-01-02,Northeast,New York,New York,Men's Athletic Footwear,50.0,1000.0,50000.0,15000.0,In-store
2,Foot Locker,1185732,2020-01-03,Northeast,New York,New York,Women's Street Footwear,40.0,1000.0,40000.0,14000.0,In-store
3,Foot Locker,1185732,2020-01-04,Northeast,New York,New York,Women's Athletic Footwear,45.0,850.0,38250.0,13388.0,In-store
4,Foot Locker,1185732,2020-01-05,Northeast,New York,New York,Men's Apparel,60.0,900.0,54000.0,16200.0,In-store
...,...,...,...,...,...,...,...,...,...,...,...,...
9656,Foot Locker,1185732,2021-01-24,Northeast,New Hampshire,Manchester,Men's Apparel,50.0,64.0,320.0,90.0,Outlet
9657,Foot Locker,1185732,2021-01-24,Northeast,New Hampshire,Manchester,Women's Apparel,41.0,105.0,431.0,138.0,Outlet
9658,Foot Locker,1185732,2021-02-22,Northeast,New Hampshire,Manchester,Men's Street Footwear,41.0,184.0,754.0,279.0,Outlet
9659,Foot Locker,1185732,2021-02-22,Northeast,New Hampshire,Manchester,Men's Athletic Footwear,42.0,70.0,294.0,123.0,Outlet
9660,Foot Locker,1185732,2021-02-22,Northeast,New Hampshire,Manchester,Women's Street Footwear,29.0,83.0,241.0,65.0,Outlet

* Create new columns from `Invoice Date`:

  * `day`
  * `month`
  * `year`

In [8]:
df['day'] = df['Invoice Date'].dt.day
df['month'] = df['Invoice Date'].dt.month
df['year'] = df['Invoice Date'].dt.year
df

,Retailer,Retailer ID,Invoice Date,Region,State,city,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Sales Method,day,month,year
0,Foot Locker,1185732,2020-01-01,Northeast,New York,New York,Men's Street Footwear,50.0,1200.0,60000.0,30000.0,In-store,1,1,2020
1,Foot Locker,1185732,2020-01-02,Northeast,New York,New York,Men's Athletic Footwear,50.0,1000.0,50000.0,15000.0,In-store,2,1,2020
2,Foot Locker,1185732,2020-01-03,Northeast,New York,New York,Women's Street Footwear,40.0,1000.0,40000.0,14000.0,In-store,3,1,2020
3,Foot Locker,1185732,2020-01-04,Northeast,New York,New York,Women's Athletic Footwear,45.0,850.0,38250.0,13388.0,In-store,4,1,2020
4,Foot Locker,1185732,2020-01-05,Northeast,New York,New York,Men's Apparel,60.0,900.0,54000.0,16200.0,In-store,5,1,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9656,Foot Locker,1185732,2021-01-24,Northeast,New Hampshire,Manchester,Men's Apparel,50.0,64.0,320.0,90.0,Outlet,24,1,2021
9657,Foot Locker,1185732,2021-01-24,Northeast,New Hampshire,Manchester,Women's Apparel,41.0,105.0,431.0,138.0,Outlet,24,1,2021
9658,Foot Locker,1185732,2021-02-22,Northeast,New Hampshire,Manchester,Men's Street Footwear,41.0,184.0,754.0,279.0,Outlet,22,2,2021
9659,Foot Locker,1185732,2021-02-22,Northeast,New Hampshire,Manchester,Men's Athletic Footwear,42.0,70.0,294.0,123.0,Outlet,22,2,2021
9660,Foot Locker,1185732,2021-02-22,Northeast,New Hampshire,Manchester,Women's Street Footwear,29.0,83.0,241.0,65.0,Outlet,22,2,2021

* Check the `Region` column and make sure there are no typos or inconsistent names.

In [9]:
print(df.columns)
df.columns = df.columns.str.strip()
df.columns

Index(['Retailer', 'Retailer ID    ', 'Invoice Date', '  Region', 'State',
       'city', 'Product', 'Price per Unit', 'Units Sold', 'Total Sales',
       'Operating Profit', 'Sales Method', 'day', 'month', 'year'],
      dtype='object')

Index(['Retailer', 'Retailer ID', 'Invoice Date', 'Region', 'State', 'city',
       'Product', 'Price per Unit', 'Units Sold', 'Total Sales',
       'Operating Profit', 'Sales Method', 'day', 'month', 'year'],
      dtype='object')

* Drop unnecessary columns such as `Retailer ID`.

In [10]:
df.drop('Retailer ID', axis=1, inplace=True)

* Handle missing values appropriately.

In [11]:
df['Price per Unit'] = df['Price per Unit'].fillna(df['Total Sales'] / df['Units Sold'])
df['Region'] = df['Region'].fillna('Unknown')

### Sales Analysis

1. What is the total sales?

In [12]:
df['Total Sales'].sum()

90494942.0

2. What is the average sales for every region?

In [13]:
df.groupby('Region')['Total Sales'].mean().round(2)

Region
Midwest       7255.92
Northeast     7966.11
South         8403.26
Southeast    13331.00
Unknown      24339.29
West         11000.87
Name: Total Sales, dtype: float64

3. What is the average sales for every product?

In [14]:
df['Product'] = df['Product'].str.replace('Men\'s aparel', 'Men\'s Apparel')

In [15]:
df.groupby('Product')['Total Sales'].mean().round(2)

Product
Men's Apparel                 7880.06
Men's Athletic Footwear       9600.41
Men's Street Footwear        12970.60
Women's Apparel              11140.40
Women's Athletic Footwear     6645.76
Women's Street Footwear       7960.39
Name: Total Sales, dtype: float64

4. What is the count of each product?

In [16]:
df['Product'].value_counts()

Product
Men's Athletic Footwear      1615
Men's Apparel                1612
Men's Street Footwear        1610
Women's Apparel              1609
Women's Street Footwear      1608
Women's Athletic Footwear    1607
Name: count, dtype: int64

5. What is the top product by total sales?

In [17]:
product_sales = (
    df.groupby('Product')['Total Sales']
    .sum().round(2).sort_values(ascending=False)
)
print(product_sales)
product_sales.index[0]

Product
Men's Street Footwear        20882669.0
Women's Apparel              17924910.0
Men's Athletic Footwear      15504660.0
Women's Street Footwear      12800313.0
Men's Apparel                12702655.0
Women's Athletic Footwear    10679735.0
Name: Total Sales, dtype: float64

"Men's Street Footwear"

6. What is the lowest-performing product by total sales?

In [18]:
product_sales.index[-1]

"Women's Athletic Footwear"

### Time Analysis

7. How many products were sold each year?

In [19]:
df['year'].value_counts()

year
2021    8349
2020    1312
Name: count, dtype: int64

8. How have total sales changed over the years?

In [20]:
df.groupby('year')['Total Sales'].sum().round(2)

year
2020    18675850.0
2021    71819092.0
Name: Total Sales, dtype: float64

9. How do sales vary month over month?

In [21]:
df.groupby('month')['Total Sales'].sum().round(2)

month
1     7363937.0
2     6110037.0
3     5680937.0
4     7250517.0
5     8164538.0
6     7490506.0
7     9548092.0
8     9216635.0
9     7766164.0
10    6512617.0
11    6806744.0
12    8584218.0
Name: Total Sales, dtype: float64

### Retailer Analysis

10. Which retailer has the highest total sales?

In [22]:
retailer_sales = (
    df.groupby('Retailer')['Total Sales']
    .sum().round(2).sort_values(ascending=False)
)
print(retailer_sales)
retailer_sales.index[0]

Retailer
West Gear        24312990.0
Foot Locker      22096528.0
Sports Direct    18247156.0
Kohl's           10211506.0
Walmart           7691100.0
Amazon            7579562.0
amazon             190350.0
foot locker        165750.0
Name: Total Sales, dtype: float64

'West Gear'

11. Which retailer has the highest operating profit?

In [23]:
retailer_price = (
    df.groupby('Retailer')['Operating Profit']
    .sum().round(2).sort_values(ascending=False)
)
print(retailer_price)
retailer_price.index[0]

Retailer
West Gear        8571819.0
Foot Locker      8107111.0
Sports Direct    7433383.0
Kohl's           3681153.0
Amazon           2820065.0
Walmart          2654877.0
amazon             61820.0
foot locker        41851.0
Name: Operating Profit, dtype: float64

'West Gear'

### Product & Profit Analysis

12. What is the most profitable product?

In [24]:
product_profit = (
    df.groupby('Product')['Price per Unit']
    .sum().round(2).sort_values(ascending=False)
)
print(product_profit)
product_profit.index[0]

Product
Women's Apparel              83044.0
Men's Apparel                81187.0
Men's Street Footwear        71221.0
Men's Athletic Footwear      70710.0
Women's Athletic Footwear    66087.0
Women's Street Footwear      64726.0
Name: Price per Unit, dtype: float64

"Women's Apparel"

13. What is the average price per unit for each product?

In [25]:
df.groupby('Product')['Price per Unit'].mean().round(2).sort_values(ascending=False)

Product
Women's Apparel              51.61
Men's Apparel                50.36
Men's Street Footwear        44.24
Men's Athletic Footwear      43.78
Women's Athletic Footwear    41.12
Women's Street Footwear      40.25
Name: Price per Unit, dtype: float64

### Geographic Analysis

14. Which region has the highest total sales?

In [26]:
region_sales = (
    df.groupby('Region')['Total Sales']
    .sum().round(2).sort_values(ascending=False)
)
print(region_sales)
region_sales.index[0]

Region
West         26919128.0
Northeast    18983237.0
Southeast    16317146.0
South        14529236.0
Midwest      13575820.0
Unknown        170375.0
Name: Total Sales, dtype: float64

'West'

15. Which city contributes the most to total sales?

In [27]:
city_sales = (
    df.groupby('city')['Total Sales']
    .sum().round(2).sort_values(ascending=False)
)
print(city_sales)
city_sales.index[0]

city
New York          4309884.0
Charleston        3997485.0
San Francisco     3453924.0
Miami             3160090.0
Portland          3054564.0
Orlando           2768290.0
Seattle           2633075.0
Houston           2616692.0
Los Angeles       2563500.0
Albany            2442784.0
Charlotte         2395657.0
New Orleans       2375082.0
Honolulu          2228245.0
Richmond          2157510.0
Denver            2116161.0
Dallas            2090292.0
Las Vegas         2085854.0
Albuquerque       1986512.0
Boise             1927690.0
Atlanta           1899750.0
Detroit           1862546.0
Cheyenne          1857754.0
Columbus          1848459.0
Knoxville         1806748.0
Birmingham        1763350.0
Manchester        1641171.0
Phoenix           1578229.0
Billings          1571090.0
Jackson           1559176.0
Anchorage         1475313.0
Burlington        1435306.0
Little Rock       1263941.0
Wilmington        1229846.0
Hartford          1157352.0
Boston            1107696.0
Oklahoma City     1062080.0
Philadelphia      1056758.0
Louisville        1007284.0
Wichita            997289.0
Chicago            995502.0
Newark             993430.0
Salt Lake City     969652.0
St. Louis          968323.0
Indianapolis       883624.0
Sioux Falls        849562.0
Providence         844687.0
Baltimore          775808.0
Fargo              773557.0
Milwaukee          772751.0
Des Moines         742403.0
Minneapolis        737807.0
Omaha              592907.0
houston             50500.0
Name: Total Sales, dtype: float64

'New York'